### ISSUE TITLE
A query details panel exists

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/appmap-js#129]
- Instead of referencing queries as events which contain a query, reference the query code object directly.
- If the query code object contains a single event, navigate directly to the event

This will clean up the usage of prepared statements:
![image](https://user-images.githubusercontent.com/8737782/111809686-a0977e00-88ab-11eb-9cc7-9dcb2cd6adc4.png)

**Comment by dustinbyrne** [comment]
Here's a good sample AppMap (drop the txt extension)
[org_owasp_webgoat_GeneralLessonTest_insecureLogin.appmap.json.txt](https://github.com/applandinc/appmap-js/files/6172647/org_owasp_webgoat_GeneralLessonTest_insecureLogin.appmap.json.txt)

**Comment by kgilpin** [comment]
Did we get WebGOAT working?

**Comment by sashahonchar** [comment]
@dustinbyrne, Is that a correct AppMap?
Why SQL query is a child of SQL query?

![image](https://user-images.githubusercontent.com/17301016/112029086-9794fe00-8b84-11eb-9ba6-fcc750d1ce83.png)

**Comment by kgilpin** [comment]
Seems impossible...
