### ISSUE TITLE
Trace port identifiers appear incorrect

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/appmap-js#212]
As if Vue had recycled a port component, in some conditions, ports can seemingly appear on the wrong node.

This bug needs to be investigated. We don't have clear steps to reproduce.

Notice that `name` is incorrectly labeled as `context`. The details panel displays the correct identifiers.
![image](https://user-images.githubusercontent.com/8737782/117714951-a4f26000-b1a5-11eb-97c5-bd06a1604943.png)

Reloading the view fixes the issue:
![image](https://user-images.githubusercontent.com/8737782/117715211-fa2e7180-b1a5-11eb-9436-77934f07a30b.png)

[Applications_list_displays_a_tiling_of_the_apps.appmap.json.txt](https://github.com/applandinc/appmap-js/files/6454604/Applications_list_displays_a_tiling_of_the_apps.appmap.json.txt)

**Comment by sashahonchar** [comment]
@dustinbyrne , I have tried many times to reproduce this issue and I can't do it. Everything works as expected.

**Comment by dustinbyrne** [comment]
This key should be based off the name of the value, not the index. Same with the inputs.
https://github.com/applandinc/appmap-js/blob/main/packages/components/src/components/trace/TraceNodeBodyDefault.vue#L13
