### ISSUE TITLE
The upload icon is changed

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/appmap-js#220]
[Figma ->](https://www.figma.com/file/FNRTuAhvCGVdsisS5J2P7i/appmap-sharing?node-id=1%3A869)
![upload-icon](https://user-images.githubusercontent.com/123787/119196411-1d81d800-ba54-11eb-964c-52d59d8513bf.png)

[Proto]([Figma proto](https://www.figma.com/proto/FNRTuAhvCGVdsisS5J2P7i/appmap-sharing?page-id=0%3A1&node-id=1%3A869&viewport=747%2C332%2C0.5905522704124451&scaling=min-zoom))

**Comment by ptrdvrk** [comment]
Quick'n'dirty idea - perhaps something combining a cloud (uploading to AppMap Cloud) and sharing might work?
Like https://cdn.iconscout.com/icon/premium/png-256-thumb/cloud-share-1807930-1534783.png

**Comment by typaulhus** [comment]
> Quick'n'dirty idea - perhaps something combining a cloud (uploading to AppMap Cloud) and sharing might work?
> Like https://cdn.iconscout.com/icon/premium/png-256-thumb/cloud-share-1807930-1534783.png

my initial thought was to have this be the AppMap Cloud icon tweaked a bit for sharing. (or not tweaked at all?)

**Comment by ptrdvrk** [comment]
OK, that should work well, too.

**Comment by ptrdvrk** [comment]
Upload icon from @typaulhus 

[appland-upload-icon.svg.txt](https://github.com/applandinc/appmap-js/files/6734467/appland-upload-icon.svg.txt)
