### ISSUE TITLE
AppMap shows a clickable link to open the source_location

### ISSUE THREAD

**Issue by kgilpin** [applandinc/appmap-js#225]
When an AppMap is recorded from a test case, the `metadata.source_location` has the path to the test case file. It would be very handy to be able to click on a link to open the test case file. Otherwise the user has to open the AppMap as JSON and dig for it.

[Figma ->](https://www.figma.com/file/nfoyu3fIXjeFZcHmilWCiA/extension-sidebar?node-id=0%3A1)

![sidebar-view-source](https://user-images.githubusercontent.com/123787/120360741-1752ed80-c2d7-11eb-97a6-a438c6d684c2.jpg)

**Comment by dustinbyrne** [comment]
@typaulhus @Daniel-Warner-X Where does this button fit in?

**Comment by typaulhus** [comment]
this makes the most sense in the top of the sodebar, but that's really cluttered at the moment. I'll add this piece in to the sidebar control organization I'm working on
