### ISSUE TITLE
Routes with media MIME types are hidden by default with a filter

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/appmap-js#235]
Hide the following MIME types by default:
- `application/javascript`
- `application/ecmascript`
- `audio/*`
- `font/*`
- `image/*`
- `text/javascript`
- `text/ecmascript`
- `text/css`
- `video/*`

**Comment by kgilpin** [comment]
Yeah I like this. This seems more useful as a filter; along with "Events
that aren't part of a request or job"
