### ISSUE TITLE
Remove the "appmap.yml" link from the "Configure AppMap" step.

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-js#283]
Let's remove this link for now.

![image](https://user-images.githubusercontent.com/42008542/125358804-63ae3600-e337-11eb-97cb-e1749b968973.png)

**Comment by sashahonchar** [comment]
Done https://github.com/applandinc/appmap-js/pull/267/commits/8598ad64ba19604a3bebb4c70228b3e23c60f990
