### ISSUE TITLE
"Configure AppMap" step: user can open the newly created appmap.yml file with the link in the Webview.

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-js#284]
At this moment, the UI only displays "appmap.yml" under the success message.

![image](https://user-images.githubusercontent.com/42008542/125360025-36628780-e339-11eb-88df-30a5b7b75605.png)

**Comment by sashahonchar** [comment]
Done https://github.com/applandinc/appmap-js/pull/267/commits/d2fe5d145a1f3bb9c97253d4a71a181a6bd194e6
