### ISSUE TITLE
Bug: List of detected test frameworks is not displaying the frameworks correctly.

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-js#285]
![image](https://user-images.githubusercontent.com/42008542/125660020-7328dad1-a0a8-4405-8859-494c52e544ed.png)

**Comment by sashahonchar** [comment]
In [one of the last commits](https://github.com/applandinc/appmap-js/pull/267/commits/2d8db9c85490215d128c2fff4ec317b9ff41a4a5) I changed `testFrameworks` from array to object.
Did you pass test frameworks in this structure?
```
{
  minitest: 'APPMAP=true bundle exec rails test',
  rspec: 'APPMAP=true bundle exec rake',
}
```

**Comment by torchello** [comment]
@sashahonchar No, it's currently just a list:
```js
get testFrameworks(): readonly string[] {
    return this.lastStatus?.test_commands?.map((command) => command.framework) || [];
  }
```
Also, it won't work properly in cases when there are multiple commands per framework. I think it's better to separate list of frameworks and list of test commands. @dustinbyrne wdyt?

**Comment by dustinbyrne** [comment]
Fixed in https://github.com/applandinc/vscode-appland/pull/265/commits/23f372ea99f05342146152701300bb3d9c34796e
