### ISSUE TITLE
Multiple test commands are not supported by the UI

### ISSUE THREAD

**Issue by torchello** [applandinc/appmap-js#287]
Do we have UI mockups for this view?
It does not seem to be implemented.

**Comment by Daniel-Warner-X** [comment]
In the design, we have a suggested command for the user to run. That command is editable. Why would we show multiple commands?

**Comment by torchello** [comment]
The most common use case would be if a testing framework does not support execution of multiple folders in a single command. We need to show N separate commands for each folder so you can choose the one to start with.
```
APPMAP=true bundle exec rake test app/controllers
```
```
APPMAP=true bundle exec rake test app/integration
```
Alternatively, we can run them all one by one. But IMO we should show them all in the UI anyway, so user can see what is going to be executed.

**Comment by torchello** [comment]
The most common use case would be if a testing framework does not support execution of multiple folders in a single command. We need to show N separate commands for each folder so you can choose the one to start with.
```
APPMAP=true bundle exec rake test app/controllers
```
```
APPMAP=true bundle exec rake test app/integration
```
Alternatively, we can run them all one by one. But IMO we should show them all in the UI anyway, so user can see what is going to be executed.

**Comment by Daniel-Warner-X** [comment]
Okay, that makes sense. To show multiple commands that will be run we can do something like this: 
![image](https://user-images.githubusercontent.com/1229326/125670435-0a8e4eef-f482-49f4-95ae-89e21d64fc9e.png)

**Comment by sashahonchar** [comment]
Done: https://github.com/applandinc/appmap-js/pull/267/commits/75203c07807cca9d2f0c95adfe47bc69f3f1a218
