### ISSUE TITLE
UI: 2 buttons are confusing after maps are recorded

### ISSUE THREAD

**Issue by torchello** [applandinc/appmap-js#288]
What is expected UI here:
![image](https://user-images.githubusercontent.com/897885/125662056-334be5cf-a2d4-4a3a-a429-36e34eff4427.png)

**Comment by Daniel-Warner-X** [comment]
In the design 'Record appmaps' changes state to 'AppMaps recorded' once an AppMap has been created. Why are we showing both states at the same time?

**Comment by torchello** [comment]
If I remember correctly there was an idea to let user rerun tests with a different command. Maybe that's a first "prototype" of this idea. But I'm not sure.

**Comment by Daniel-Warner-X** [comment]
For now, once an AppMap is created we should switch to the 'AppMap recorded' state. If no AppMap was recorded they should be prompted with the appropriate error message ( https://www.figma.com/file/J7ZXZhlewuPvFX4Z9e35oY/Milestones-User-Flow-(emphasis-on-content)?node-id=5%3A354 ) If we want to give them the option to re-run the test after modifying the command we can tell them that in the copy of the error message.

**Comment by Daniel-Warner-X** [comment]
Here is an optional Error page for the test step that includes the option for the user to modify the command and re-run tests: 
![image](https://user-images.githubusercontent.com/1229326/125669108-43a7ffab-5274-405e-8e44-1842f34afb19.png)

**Comment by torchello** [comment]
Should be handled in https://github.com/applandinc/appmap-js/issues/274.

**Comment by sashahonchar** [comment]
Done: https://github.com/applandinc/appmap-js/pull/267/commits/0d08ed32c77d8cb806dde7268886ca9819e06df7
