### ISSUE TITLE
Shallow-recorded AppMaps with spring framework calls aren't rendered correctly

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-js#325]
Something in the shallow-recorded AppMaps of `org.springframework.web` is tripping the local processing of the AppMap data in the javascript components.
 - Without `org.springframework.web` in appmap.yml  , the `GET` and `POST` requests captured are accurate
 - With `org.springframework.web`, `shallow:true`  , the http requests are repeated in the diagrams and their numbers multiplied, but the data is correct; it’s just the visualization that is incorrect.

![image](https://user-images.githubusercontent.com/42008542/131710220-d0cc8090-0d41-4481-9298-27579ac7fe9d.png)

![image](https://user-images.githubusercontent.com/42008542/131710236-08a9fbd3-8a2d-4768-8013-965a4e2c8ebb.png)

[Spring_Find_Owner.appmap.json.zip](https://github.com/applandinc/appmap-js/files/7092931/Spring_Find_Owner.appmap.json.zip)

[appmap.yml.txt](https://github.com/applandinc/appmap-js/files/7092934/appmap.yml.txt)

**Comment by sashahonchar** [comment]
@ptrdvrk , @dustinbyrne I think there is not an issue, because events duplicate in AppMap file, not only on the diagrams.

**Comment by ptrdvrk** [comment]
Looks like I've attached a wrong appmap in a rush, let me see if I can find a better one.

**Comment by ptrdvrk** [comment]
I can't reproduce this anymore, closing.
