### ISSUE TITLE
Python projects can optionally choose to run `pip install appmap` if no `poetry.lock`, `Pipfile`, `requirements.txt` exists.

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/appmap-js#372]

**Comment by kgilpin** [comment]
Would a Django or Flask project realistically have this issue?

**Comment by apotterri** [comment]
> Would a Django or Flask project realistically have this issue?
No. So far, the absence of any sort of package manager in a python project has indicated that it's a toy, with just a couple of source files.

**Comment by kgilpin** [comment]
So this can’t really be a high priority then.

The real fix is to get the user into a better project.
