### ISSUE TITLE
`Set as root` can be performed from the left sidebar

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/appmap-js#399]
A button exists which adds the current code object as a root code object in the class map.

__WIP__ (from [Figma](https://www.figma.com/file/T72cGO1asVVPg40ZioWwXa/custom-views?node-id=32%3A622))
![image](https://user-images.githubusercontent.com/8737782/136097199-a0ea7e45-ea64-451b-9d1d-b9c787ebab5a.png)

**Comment by kgilpin** [comment]
@dustinbyrne @typaulhus did we decide if this is a checkbox or a button? The mockup shows a Checkbox but the title says Button.
