### ISSUE TITLE
Event list items are visibly distinct

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/appmap-js#40]
![image](https://user-images.githubusercontent.com/8737782/104746817-c377ab80-571d-11eb-9192-c4c240a675ad.png)

Is there a better way we can list distinct events without including a numeric ID?

**Comment by ptrdvrk** [comment]
We could visually separate function calls from REST and SQL calls, and within function calls, identify calls within the same package vs. calls to other packages?
