### ISSUE TITLE
Map UI controls are updated

### ISSUE THREAD

**Issue by typaulhus** [applandinc/appmap-js#418]
- Dependency & Trace map tabs matches designs
- Left-column search bar is moved into Dependency Map tab. This will search for code objects 
- Trace tab search bar for events in Trace view.
- Filter icon (top right of tab) toggles filters
- searchbar removed from left column (moving to dependency tab)

[Figma ->](https://www.figma.com/file/T72cGO1asVVPg40ZioWwXa/custom-views?node-id=242%3A5554)

![custom_views_trace](https://user-images.githubusercontent.com/123787/137388588-1f4f89f0-b1d1-4446-b825-71cb85698053.jpg)

**Comment by kgilpin** [comment]
I think Code Objects panel should always be visible. Because we also use
that when the user clicks on an event, to show event details. The user may
not know how to find it if it disappears when switching to the Trace view.
