### ISSUE TITLE
Users can cycle through search results

### ISSUE THREAD

**Issue by typaulhus** [applandinc/appmap-js#419]
When users perform a search in either the Trace, or Dependency maps, their results will be highlighted in the map. 

If there are multiple results, users are able to cycle through these... the map will change the highlighted item, a count badge will be displayed, and the left column will display the details for the highlighted item
 
[Figma ->](https://www.figma.com/proto/T72cGO1asVVPg40ZioWwXa/custom-views?page-id=144%3A4603&node-id=144%3A7831&viewport=363%2C48%2C0.74&scaling=min-zoom&starting-point-node-id=144%3A5102)

![search-results](https://user-images.githubusercontent.com/123787/137389387-253cd712-99f9-499d-9f5c-3ff57e5d1446.gif)
.

**Comment by kgilpin** [comment]
A search term can be a string that matches a code object (and it’s events
in the Trace) or it can be an event id.

The search can have multiple terms.

A common case is that the search terms are event ids (one or more than
one).
