### ISSUE TITLE
Event search in trace matches labels

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/appmap-js#464]
The search bar in the trace view allows `label` search terms and highlights every event with the given label(s). If more than one label is provided, all labels must match.

![image](https://user-images.githubusercontent.com/8737782/143097702-078ea4fe-2973-443f-bd9a-e411afe47053.png)

**Comment by kgilpin** [comment]
Keep up the good progress guys.

Please remember that we want to be able to set these view settings via
launch URL.
