### ISSUE TITLE
Record AppMap messaging in Getting Started is updated with status of Python

### ISSUE THREAD

**Issue by typaulhus** [applandinc/appmap-js#636]
Add a message to Record AppMaps section in Quickstart to display the status of Python availability.

![Image](https://user-images.githubusercontent.com/123787/174824965-b75d1c32-9725-4071-91a3-f6e25da16855.png)

**Comment by dividedmind** [comment]
I believe this has been fixed by https://github.com/applandinc/appmap-js/pull/635
