### ISSUE TITLE
The heading on the 'Open AppMaps' page is too small

### ISSUE THREAD

**Issue by Daniel-Warner-X** [applandinc/appmap-js#658]
"Open AppMaps" should be the same size as the heading on "Install AppMap Agent" and other instructions views.

![Image](https://user-images.githubusercontent.com/1229326/176792463-66f62ed7-d50d-4b7f-87a5-cb3efdbf1a17.png)

**Comment by typaulhus** [comment]
Fixed: https://github.com/applandinc/appmap-js/pull/715
