### ISSUE TITLE
`scan --watch` does not scan existing unscanned indexes

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/appmap-js#727]

**Comment by jansorg** [comment]
@brikelly I think this is impacting the IntelliJ install guide PR. 
The appmap and scanner processes are launched when a new appmap.yml file was detected by IntelliJ's file watcher . The file watcher may pick up the appmap.yml file after .appmap.json files were already created.
In that case the AppMap would not be properly indexed and scanner.

**Comment by brikelly** [comment]
Apparently this might be solvable by changing the value of the "ignore initial" flag to how we call chokidar.
